GET http://localhost:3002/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3002/api/v1/person HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3002/api/v1/person/5fd7874e18aa776a9bee3b6a HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3002/api/v1/person HTTP/1.1
Content-Type: application/json

{
    "name": "Miguel Eduardo",
    "lastname": "Quero"
}
###

PUT http://localhost:3002/api/v1/person/5fd7875318aa776a9bee3b6b HTTP/1.1
Content-Type: application/json

{
    "name": "Frank"
}
###

DELETE http://localhost:3002/api/v1/person/5fd7874e18aa776a9bee3b6a HTTP/1.1
Content-Type: application/json

###